
boxes = [
    {
        :node_name => "node1",
        :node_managementip => "10.0.200.11",
        :node_serviceip => "192.168.200.11",
        :node_mem => "2048",
        :node_cpu => "1"
    },
    {
      :node_name => "node2",
      :node_managementip => "10.0.200.12",
      :node_serviceip => "192.168.200.12",
      :node_mem => "2048",
      :node_cpu => "1"
    },
    {
      :node_name => "node3",
      :node_managementip => "10.0.200.13",
      :node_serviceip => "192.168.200.13",
      :node_mem => "2048",
      :node_cpu => "1"
    }
]

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  boxes.each do |opts|
    config.vm.define opts[:node_name] do |config|
      config.vm.hostname = opts[:node_name]

      config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--memory", opts[:node_mem]]
        v.customize ["modifyvm", :id, "--cpus", opts[:node_cpu]]
      end

      config.vm.network "private_network",
      ip: opts[:node_managementip],
      virtualbox__intnet: "DOCKER_MANAGEMENT"

      config.vm.network "private_network",
      ip: opts[:node_serviceip],
      virtualbox__intnet: "DOCKER_SERVICE"

      config.vm.network "public_network",
      bridge: "wlan0",
      use_dhcp_assigned_default_route: true

      config.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update -y
      SHELL

    end
  end
end
